version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/app/api
    ports:
      - 8000:8000
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm run start
    volumes:
      - ./frontend/:/usr/src/app/frontend
    ports:
      - 3000:3000

